### ISSUE TITLE
Issue with PyCurl

### ISSUE THREAD

**Issue by imrane** [the-praxs/DeFiLlama-Curl#4]
Receive the following error:
```
Traceback (most recent call last):
  File "/Users/####/Sites/####/####/dl.py", line 3, in <module>
    from defillama.tvl import get_protocol_tvl
  File "/Users/#####/Sites/####/#######/venv/lib/python3.11/site-packages/defillama/tvl.py", line 2, in <module>
    from ._utils import get
  File "/Users/####/Sites/#####/#######/venv/lib/python3.11/site-packages/defillama/_utils.py", line 1, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)
```
I checked my pycurl
```
Name: pycurl
Version: 7.45.2
Summary: PycURL -- A Python Interface To The cURL library
Home-page: http://pycurl.io/
Author: Kjetil Jacobsen, Markus F.X.J. Oberhumer, Oleg Pudeyev
Author-email: kjetilja@gmail.com, markus@oberhumer.com, oleg@bsdpower.com
License: LGPL/MIT
Location: /Users/###/Sites/###/###-###/venv/lib/python3.11/site-packages
Requires: 
Required-by: DeFiLlama-Curl
```

**Comment by imrane** [comment]
Fixed it with this 
https://stackoverflow.com/a/74173308/1240798

**Comment by dot-agi** [comment]
Does this require any source code/deps modifications?

**Comment by imrane** [comment]
Not sure...the fix for me was to compile it directly

**Comment by dot-agi** [comment]
Closing this because its resolved and a PyCurl issue at the end.
